import React,{useState,useRef,useEffect} from 'react';
import { Camera,FileText,Plus,Trash2,Check,Loader2,Package,CalendarDays,ChevronDown,AlertCircle } from 'lucide-react';
import { Sheet } from '../Sheet';
import { Field,inputClass } from '../FormNav';
import { TextInput } from '../TextInput';
import { NumberInput } from '../NumberInput';
import { DateField,swissToday,toIsoDate } from '../DateField';
import { Combobox } from '../Combobox';
import { StorageService } from '../../services/storage';
import { GeminiScannerService,type ScanOutcome,type ScannedLineKind } from '../../services/geminiScanner';
import { savePurchaseWithProof,confirmPurchase,validatePurchase,purchaseDuplicates,type PurchaseDraft,type PurchaseLineDraft } from '../../services/purchaseEntry';
import { isConfirmedWriteRejection } from '../../services/firestoreRepo';
import type { FinanceCategory } from '../../types';
import { FinanceService } from '../../services/financeService';
import { planOccurrences } from '../../domain/finance/forecast';
import { DriveConnection } from './DriveConnection';
import { InvoiceScanReview } from './InvoiceScanReview';
import { invoiceTotalProposal,invoiceFieldHints,invoicePurchaseDescription,patchPurchaseDraft,scannedPayment } from '../../services/purchasePrefill';

export interface ExpenseSheetProps { onClose:()=>void;onSaved:()=>void;initialIntent?:'expense'|'equipment';existingEquipmentId?:string;startWithScan?:boolean;initialPlanId?:string }
const kinds:Array<{value:PurchaseLineDraft['kind'];label:string}>=[{value:'ingredient',label:'Ingrédients'},{value:'packaging',label:'Emballages'},{value:'cleaning',label:'Nettoyage'},{value:'equipment',label:'Matériel durable'},{value:'maintenance',label:'Entretien / réparation'},{value:'service',label:'Service'},{value:'shipping',label:'Livraison'},{value:'discount',label:'Remise'},{value:'other',label:'Autre'}];
type PurchaseCategory=Exclude<FinanceCategory,'apports'|'recettes'>;
const categories:Array<{value:PurchaseCategory;label:string}>=[{value:'brassage',label:'Brassage'},{value:'materiel',label:'Matériel'},{value:'nettoyage',label:'Nettoyage'},{value:'chargesFixes',label:'Charges fixes'},{value:'renovation',label:'Local'},{value:'divers',label:'Autre'}];
const money=(n:number)=>new Intl.NumberFormat('fr-CH',{style:'currency',currency:'CHF'}).format(n);
const newLine=(intent='expense'):PurchaseLineDraft=>({id:crypto.randomUUID(),description:'',kind:intent==='equipment'?'equipment':'ingredient',unit:'',stockAction:'none',equipmentAction:intent==='equipment'?'new':'none'});
const scanKind=(kind:ScannedLineKind):PurchaseLineDraft['kind']=>kind==='stock'?'ingredient':kind==='unknown'?'other':kind;
const button='min-h-12 rounded-control px-3 text-sm font-medium border transition-colors';
const dayShortcuts=[{label:'Hier',offsetDays:-1},{label:"Aujourd’hui",offsetDays:0},{label:'Demain',offsetDays:1}];
const uncertainClass='rounded-control border border-amber-400/50 bg-amber-400/5 p-2';
function ScanHint({field,message}:{field:string;message?:string}) {
  return message?<p id={`scan-hint-${field}`} className="text-xs text-amber-200 leading-relaxed flex gap-1.5 mt-1.5"><AlertCircle size={14} className="shrink-0 mt-0.5"/><span><strong className="font-medium">À confirmer · </strong>{message}</span></p>:null;
}

export function ExpenseSheet({onClose,onSaved,initialIntent='expense',existingEquipmentId,startWithScan=false,initialPlanId}:ExpenseSheetProps) {
  const [draft,setDraft]=useState<PurchaseDraft>(()=>{
    const plan=initialPlanId?FinanceService.getPlans().find(p=>p.id===initialPlanId):undefined;
    return {submissionId:crypto.randomUUID(),date:swissToday(),vendor:plan?.vendor??'',invoiceNumber:'',description:plan?.title??'',planId:initialPlanId,category:initialIntent==='equipment'?'materiel':'brassage',lines:[{...newLine(initialIntent),description:plan?.title??'',...(existingEquipmentId?{equipmentAction:'existing' as const,equipmentRef:existingEquipmentId}: {})}],paymentStatus:'paid',paymentMethod:'bank',paymentDate:swissToday(),dueDate:'',sourceCurrency:'CHF'};
  });
  const [scan,setScan]=useState<ScanOutcome|null>(null),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[attachment,setAttachment]=useState<File|null>(null),[pendingId,setPendingId]=useState<string|null>(null);
  const [showForm,setShowForm]=useState(!startWithScan&&(initialIntent==='equipment'||Boolean(initialPlanId)));
  const fileInput=useRef<HTMLInputElement>(null),cameraInput=useRef<HTMLInputElement>(null),scanLocked=useRef(false),mounted=useRef(true),saveLocked=useRef(false),form=useRef<HTMLDivElement>(null),errorBox=useRef<HTMLDivElement>(null);
  const manuallyClassified=useRef(new Set<string>());
  const [driveAuthError,setDriveAuthError]=useState(false);
  const [reviewedFields,setReviewedFields]=useState<string[]>([]);
  const hints=scan?.ok&&scan.result?Object.fromEntries(Object.entries(invoiceFieldHints(scan.result)).filter(([field])=>!reviewedFields.includes(field))):{};
  const reviewed=(field:string)=>setReviewedFields(previous=>previous.includes(field)?previous:[...previous,field]);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  useEffect(()=>{if(error)errorBox.current?.scrollIntoView({block:'nearest'});},[error]);
  const stocks=StorageService.getStocks(),transactions=StorageService.getTransactions();
  const plans=FinanceService.getPlans().filter(plan=>(plan.status==='active'||plan.source==='equipment'&&plan.status==='draft')&&plan.direction==='out'),selectedPlan=plans.find(plan=>plan.id===draft.planId);
  const occurrences=selectedPlan?.recurrence?planOccurrences(selectedPlan,`${new Date().getFullYear()-1}-01-01`,`${new Date().getFullYear()+2}-12-31`):[];
  const patch=(value:Partial<PurchaseDraft>)=>{setDraft(previous=>patchPurchaseDraft(previous,value,swissToday()));};
  const updateLine=(id:string,value:Partial<PurchaseLineDraft>)=>{setDraft(previous=>({...previous,lines:previous.lines.map(line=>line.id===id?{...line,...value}:line)}));};
  const simplePurchase=draft.lines.length===1&&!scan?.ok&&draft.lines[0].description===draft.description&&draft.lines[0].amount===draft.amount;
  const selectCategory=(category:PurchaseCategory)=>{
    const line=draft.lines[0];
    const suggestedKind:Record<PurchaseCategory,PurchaseLineDraft['kind']>={brassage:'ingredient',materiel:'equipment',nettoyage:'cleaning',chargesFixes:'service',renovation:'service',divers:'other'};
    patch({category,...(simplePurchase&&!manuallyClassified.current.has(line.id)&&line.stockAction==='none'&&line.equipmentAction==='none'?{lines:[{...line,kind:suggestedKind[category]}]}:{})});
  };
  const errors=validatePurchase(draft,stocks,transactions),duplicates=purchaseDuplicates(draft,transactions);
  const attach=async(file:File)=>{
    if(scanLocked.current||saveLocked.current)return;
    if(file.size>4*1024*1024 || !['image/jpeg','image/png','image/webp','application/pdf'].includes(GeminiScannerService.normalizeMimeType(file))){setError('Choisis un JPG, PNG, WebP ou PDF de 4 Mo maximum.');return;}
    if(attachment&&scan?.ok)patch({amount:undefined,vendor:'',invoiceNumber:'',description:'',date:swissToday(),lines:[newLine(initialIntent)],sourceCurrency:'CHF',sourceAmount:undefined,sourceNetAmount:undefined,sourceVatRate:undefined,sourceVatAmount:undefined,scanModel:undefined,sourceDocumentType:undefined,sourceOrderNumber:undefined,sourceTotalBasis:undefined});
    scanLocked.current=true;setBusy(true);setError('');setScan(null);setReviewedFields([]);
    try {
      const proofDataUrl=await GeminiScannerService.fileToDataUrl(file);
      const digest=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());
      const documentHash=Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');
      if(!mounted.current)return;
      setAttachment(file);
      patch({proofDataUrl,proofFileName:file.name,proofType:GeminiScannerService.normalizeMimeType(file),documentHash});
      const outcome=await GeminiScannerService.scanDocument(file);
      if(!mounted.current)return;
      setScan(outcome);
      if(!outcome.ok || !outcome.result){setError(outcome.error||'Le scan n’a pas abouti. Les champs restent modifiables.');return;}
      const result=outcome.result;
      const total=invoiceTotalProposal(result);
      const description=invoicePurchaseDescription(result);
      const lines=result.items.map(item=>({id:item.id,description:[item.name,item.variant].filter(Boolean).join(' · '),kind:scanKind(item.kind),amount:result.currency==='CHF'?(item.amountTTC??undefined):undefined,quantity:item.quantity??undefined,unit:item.unit,stockAction:'none' as const,equipmentAction:'none' as const,stockCategory:item.stockCategory,sourceReference:item.reference,evidence:[item.reference?`Réf. ${item.reference}`:'',item.evidence].filter(Boolean).join(' · ')}));
      manuallyClassified.current.clear();
      patch({vendor:result.vendor,date:result.date,...scannedPayment(result,swissToday()),invoiceNumber:result.invoiceNumber,description,category:result.category,amount:total.amount,lines:lines.length?lines:[{...newLine(),description:description||'Achat',amount:total.amount}],sourceCurrency:result.currency,sourceAmount:result.amountTTC??undefined,sourceDocumentType:result.documentType,sourceOrderNumber:result.orderNumber,sourceTotalBasis:total.calculated?'line_sum':result.amountTTC!==null?'printed':undefined,sourceNetAmount:result.amountHT??undefined,sourceVatRate:result.tvaRate??undefined,sourceVatAmount:result.tvaAmount??undefined,scanModel:outcome.model,documentHash});
    }catch(e:any){if(mounted.current)setError(e.message||'Lecture indisponible. Saisis les informations manuellement.');}
    finally{scanLocked.current=false;if(mounted.current){setBusy(false);setShowForm(true);}}
  };
  const save=async()=>{
    if(saveLocked.current||scanLocked.current)return;
    if(scan?.ok&&scan.result?.documentType==='credit_note'){setError('Ce document est un avoir. Enregistre-le comme remboursement dans Finances, ou joins la facture de l’achat.');return;}
    if(errors.length){form.current?.querySelectorAll('details[data-purchase-options]').forEach(element=>{(element as HTMLDetailsElement).open=true;});setError(errors.join('\n'));return;}
    if(selectedPlan?.recurrence&&!draft.occurrenceId){setError('Sélectionne l’échéance de la dépense prévue.');return;}
    saveLocked.current=true;setSaving(true);setError('');
    try {
      const id=pendingId||await savePurchaseWithProof(draft);setPendingId(id);
      await confirmPurchase(draft);
      if(mounted.current){onSaved();onClose();}
    }catch(e:any){if(mounted.current){if(isConfirmedWriteRejection(e))setPendingId(null);if(e?.code==='drive/auth-required')setDriveAuthError(true);setError(e.message||'L’enregistrement reste à confirmer.');}}
    finally{saveLocked.current=false;if(mounted.current)setSaving(false);}
  };
  const setTotal=(amount:number|undefined)=>{if(amount!==draft.amount)reviewed('amountTTC');setDraft(previous=>({...previous,amount,lines:previous.lines.length===1?[{...previous.lines[0],amount}]:previous.lines,duplicateConfirmed:false}));};
  const stockOptions=[...stocks.rawMaterials,...stocks.cleaning].map(item=>({value:item.ref,label:item.name,detail:`${item.currentStock} ${item.unit} · ${item.category}`}));
  const equipmentOptions=stocks.equipment.map(item=>({value:item.ref,label:item.name,detail:item.category}));
  return <Sheet open onClose={()=>{if(!busy&&!saving)onClose();}} dismissible={!busy&&!saving} title={initialIntent==='equipment'?'Acheter du matériel':'Nouvelle dépense'} subtitle={showForm?'Vérifie les informations, puis enregistre.':'Photo ou fichier, puis confirme.'} footer={showForm&&!busy?<button type="button" disabled={saving} onClick={()=>void save()} className={`${button} w-full bg-ebc-straw border-ebc-straw text-cave-950 disabled:opacity-40 inline-flex items-center justify-center gap-2 font-semibold`}>{saving?<Loader2 size={18} className="animate-spin"/>:<Check size={18}/>} {saving?'Enregistrement…':pendingId?'Vérifier la synchronisation':scan?.ok?'Confirmer et enregistrer':'Enregistrer la dépense'}</button>:null}>
    {error?<div ref={errorBox} role="alert" className="rounded-panel bg-amber-400/10 border border-amber-400/25 p-3 text-sm text-amber-200 whitespace-pre-line">{error}</div>:null}
    {draft.proofDataUrl&&!busy?<DriveConnection always={driveAuthError} onConnected={()=>{setDriveAuthError(false);setError('');}}/>:null}
    <div className="space-y-3 pb-2" ref={form}>
      <input ref={fileInput} aria-label="Importer un justificatif" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" className="hidden" onChange={e=>{const file=e.target.files?.[0];if(file)void attach(file);e.target.value='';}}/>
      <input ref={cameraInput} aria-label="Photographier un justificatif" type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>{const file=e.target.files?.[0];if(file)void attach(file);e.target.value='';}}/>
      {!attachment&&!busy?showForm?<button type="button" disabled={saving||Boolean(pendingId)} onClick={()=>fileInput.current?.click()} className={`${button} w-full border-cave-700 text-cave-300 flex items-center justify-center gap-2`}><FileText size={18}/>Joindre un justificatif</button>:<section className="rounded-panel border border-cave-700 bg-cave-850/50 p-4 space-y-3">
        <button type="button" onClick={()=>cameraInput.current?.click()} className="w-full min-h-16 rounded-control bg-ebc-straw text-cave-950 flex items-center justify-center gap-3 font-semibold"><Camera size={22}/>Prendre une photo</button>
        <button type="button" onClick={()=>fileInput.current?.click()} className={`${button} w-full border-cave-600 text-cave-50 flex justify-center items-center gap-2`}><FileText size={18}/>Importer un fichier</button>
        <p className="text-xs text-center text-cave-400">Photo ou PDF · lecture automatique · 4 Mo max.</p>
        {!showForm?<button type="button" onClick={()=>setShowForm(true)} className="min-h-11 w-full text-sm text-cave-300 underline underline-offset-4">Saisir sans justificatif</button>:null}
      </section>:busy||!scan?.ok?<div className="rounded-panel border border-cave-700 p-3 flex gap-3 items-center">
        {busy?<Loader2 size={20} className="animate-spin text-ebc-straw shrink-0"/>:<FileText size={20} className="text-hop shrink-0"/>}
        <div className="min-w-0 flex-1"><p role={busy?'status':undefined} className="text-sm font-medium text-cave-50">{busy?'Lecture et vérification…':'Justificatif prêt'}</p><p className="truncate text-xs text-cave-400">{attachment?.name||'Préparation de la photo…'}</p></div>
        {!busy?<button type="button" disabled={saving||Boolean(pendingId)} onClick={()=>fileInput.current?.click()} className="min-h-11 text-sm text-ebc-straw">Changer</button>:null}
      </div>:null}
      {showForm&&!busy?<fieldset disabled={saving||Boolean(pendingId)} className="space-y-3 min-w-0">
      {scan?.ok&&scan.result?<InvoiceScanReview result={scan.result} cached={scan.cached} compact/>:null}
      {draft.proofDataUrl?<div className="flex items-start gap-3"><details className="text-sm text-cave-300 flex-1 min-w-0"><summary className="min-h-11 cursor-pointer flex items-center gap-2"><FileText size={16}/>Voir le justificatif</summary>{draft.proofType?.startsWith('image/')?<img src={draft.proofDataUrl} alt="Justificatif source" className="w-full rounded-panel"/>:<a href={draft.proofDataUrl} download={draft.proofFileName} className="text-ebc-straw min-h-11 flex items-center">Ouvrir le PDF original</a>}</details>{scan?.ok?<button type="button" onClick={()=>fileInput.current?.click()} className="text-sm text-ebc-straw min-h-11">Changer</button>:null}</div>:null}
      <div className={hints.amountTTC?uncertainClass:''}><Field label="Total TTC en CHF" htmlFor="purchase-total"><NumberInput id="purchase-total" aria-describedby={hints.amountTTC?'scan-hint-amountTTC':undefined} value={draft.amount} onValue={setTotal} emptyValue={undefined} min={0} placeholder="0.00" className={`${inputClass} !text-2xl font-semibold tabular-nums h-14`}/></Field><ScanHint field="amountTTC" message={hints.amountTTC}/></div>
      {draft.sourceCurrency&&draft.sourceCurrency!=='CHF'?<p className="text-amber-200 text-sm">Original : {draft.sourceAmount??'montant absent'} {draft.sourceCurrency}. Montants à renseigner en CHF.</p>:null}
      <Field label="Pour quoi ?" htmlFor="purchase-description"><TextInput id="purchase-description" value={draft.description} onChange={description=>{patch({description});if(draft.lines.length===1)updateLine(draft.lines[0].id,{description});}} placeholder={initialIntent==='equipment'?'Fermenteur 30 L, pompe de brassage…':'Malt pour la Pale Ale, entretien de la pompe…'}/></Field>
      <details data-purchase-options open={Boolean(hints.date)} className={`rounded-panel border p-3 ${hints.date?'border-amber-400/50 bg-amber-400/5':'border-cave-800'}`}><summary className="min-h-11 cursor-pointer flex items-center gap-2 text-sm text-cave-200"><CalendarDays size={18} className="text-cave-400"/><span className="flex-1">Achat du <strong className="font-medium text-cave-50">{draft.date||'…'}</strong></span><span className="text-xs text-ebc-straw">Modifier</span><ChevronDown size={14}/></summary><ScanHint field="date" message={hints.date}/><div className="pt-2"><DateField label="Date de l’achat" value={draft.date} onChange={date=>{reviewed('date');patch({date});}} shortcuts={dayShortcuts} monthShortcuts/></div></details>
      <section className={hints.paymentEvidence?`${uncertainClass} space-y-2`:'space-y-2'} aria-label="Règlement"><div className="grid grid-cols-2 gap-2">{([{value:'paid',label:'Déjà payé'},{value:'unpaid',label:'À payer'}] as const).map(status=><button key={status.value} type="button" aria-pressed={draft.paymentStatus===status.value} onClick={()=>{reviewed('paymentEvidence');patch({paymentStatus:status.value,...(status.value==='paid'&&toIsoDate(draft.paymentDate)>toIsoDate(swissToday())?{paymentDate:swissToday()}:{})});}} className={`${button} ${draft.paymentStatus===status.value?status.value==='paid'?'border-hop/60 text-hop bg-hop/10':'border-ebc-straw text-ebc-straw bg-ebc-straw/10':'border-cave-700 text-cave-300'}`}>{status.value==='paid'?<Check size={15} className="inline mr-1.5"/>:null}{status.label}</button>)}</div>
        <ScanHint field="paymentEvidence" message={hints.paymentEvidence}/>
        <details data-purchase-options className="text-sm text-cave-300"><summary className="min-h-11 cursor-pointer flex items-center justify-between gap-2"><span>{draft.paymentStatus==='paid'?`Payé le ${draft.paymentDate||'…'}`:draft.dueDate?`Échéance : ${draft.dueDate}`:'Ajouter une échéance'}</span><ChevronDown size={14}/></summary><div className="space-y-3 pb-2">{draft.paymentStatus==='paid'?<><DateField label="Date du paiement" value={draft.paymentDate} onChange={paymentDate=>patch({paymentDate})} shortcuts={dayShortcuts} monthShortcuts/><Field label="Moyen de paiement" htmlFor="purchase-payment-method"><select id="purchase-payment-method" className={inputClass} value={draft.paymentMethod} onChange={e=>patch({paymentMethod:e.target.value as any})}><option value="bank">Compte bancaire / carte</option><option value="cash">Espèces</option><option value="twint">TWINT</option><option value="other">Autre</option></select></Field></>:<DateField label="Échéance (facultative)" value={draft.dueDate} onChange={dueDate=>patch({dueDate})} shortcuts={dayShortcuts} monthShortcuts/>}</div></details>
      </section>
      <details data-purchase-options open={Boolean(hints.vendor||hints.category)} className="rounded-panel border border-cave-800 p-3"><summary className="list-none relative pr-6 min-h-11 cursor-pointer text-sm text-cave-200"><ChevronDown size={14} className="absolute right-0 top-3"/><span className="block">Fournisseur et catégorie</span><span className="block text-xs text-cave-400 mt-1 break-words">{draft.vendor||'Fournisseur facultatif'} · {categories.find(c=>c.value===draft.category)?.label}</span></summary><div className="space-y-3 pt-3">
      <div className={hints.category?uncertainClass:''}><Field label="Catégorie" htmlFor="purchase-category"><select id="purchase-category" value={draft.category} onChange={e=>{reviewed('category');selectCategory(e.target.value as PurchaseCategory);}} className={inputClass}>{categories.map(category=><option key={category.value} value={category.value}>{category.label}</option>)}</select></Field><ScanHint field="category" message={hints.category}/></div>
      <div className={hints.vendor?uncertainClass:''}><Field label="Fournisseur" htmlFor="purchase-vendor"><TextInput id="purchase-vendor" value={draft.vendor} onChange={vendor=>{reviewed('vendor');patch({vendor});}} placeholder="Nom du fournisseur"/></Field><ScanHint field="vendor" message={hints.vendor}/></div>
      </div></details>
      {plans.length?<details className="rounded-panel border border-cave-800 p-3" open={Boolean(selectedPlan)}><summary className="min-h-12 flex items-center text-sm text-cave-300 cursor-pointer">Lier à une dépense prévue (facultatif)</summary><div className="space-y-2 pt-2"><Field label="Dépense prévue" htmlFor="purchase-plan"><select id="purchase-plan" className={inputClass} value={draft.planId||''} onChange={e=>patch({planId:e.target.value||undefined,occurrenceId:undefined})}><option value="">Aucune prévision liée</option>{plans.map(plan=><option key={plan.id} value={plan.id}>{plan.title}</option>)}</select></Field>{selectedPlan?.recurrence?<Field label="Échéance concernée" htmlFor="purchase-occurrence"><select id="purchase-occurrence" className={inputClass} value={draft.occurrenceId||''} onChange={e=>patch({occurrenceId:e.target.value||undefined})}><option value="">Choisir l’échéance</option>{occurrences.map(occurrence=><option key={occurrence.id} value={occurrence.id}>{occurrence.date}</option>)}</select></Field>:null}<p className="text-xs text-cave-500">L’achat remplacera le montant prévu correspondant.</p></div></details>:null}
      <details data-purchase-options className="rounded-panel border border-cave-800 p-3" open={initialIntent==='equipment'}><summary className="list-none relative pr-6 min-h-11 cursor-pointer text-sm text-cave-200"><ChevronDown size={14} className="absolute right-0 top-3"/><span className="block">Articles, stock et matériel · {draft.lines.length}{hints.items?<span className="ml-2 text-amber-200 text-xs">À vérifier</span>:null}</span><span className="block text-xs text-cave-400 mt-1">{[...new Set(draft.lines.map(line=>kinds.find(kind=>kind.value===line.kind)?.label))].join(' · ')}</span>{draft.lines.some(line=>line.stockAction!=='none'||line.equipmentAction!=='none')?<span className="block mt-1 text-ebc-straw">{draft.lines.filter(line=>line.stockAction!=='none').length} entrée(s) en stock · {draft.lines.filter(line=>line.equipmentAction!=='none').length} fiche(s) matériel</span>:null}</summary><ScanHint field="items" message={hints.items}/><div className="space-y-3 pt-3"><div className="flex justify-between gap-2 items-center"><h3 className="font-semibold text-cave-100">Ce que tu achètes</h3>{draft.lines.length>1?<button type="button" className="text-xs text-cave-400 min-h-11" onClick={()=>patch({lines:[{...newLine(),description:draft.description,kind:'other',amount:draft.amount}]})}>Regrouper en une dépense</button>:null}</div>
        {scan?.ok?<p className="text-xs text-cave-400 leading-relaxed">Les types d’achat sont proposés depuis le justificatif. Tu choisis ensuite les entrées en stock et les fiches matériel.</p>:null}
        {draft.lines.map((line,index)=><article key={line.id} className="rounded-panel border border-cave-700 p-3 space-y-3">
          {!simplePurchase&&<div className="flex items-center gap-2"><span className="text-xs text-cave-500 w-4">{index+1}</span><div className="flex-1 min-w-0"><TextInput aria-label={`Libellé ligne ${index+1}`} value={line.description} onChange={description=>updateLine(line.id,{description})} placeholder="Article ou prestation"/></div>{draft.lines.length>1?<button type="button" aria-label={`Retirer la ligne ${index+1}`} onClick={()=>patch({lines:draft.lines.filter(item=>item.id!==line.id)})} className="min-h-11 min-w-11 text-cave-400 flex justify-center items-center"><Trash2 size={17}/></button>:null}</div>}
          <div className={simplePurchase?'':'grid grid-cols-[1fr_7.5rem] gap-2'}><Field label="Type d’achat"><select aria-label={`Nature ligne ${index+1}`} value={line.kind} onChange={e=>{manuallyClassified.current.add(line.id);updateLine(line.id,{kind:e.target.value as PurchaseLineDraft['kind'],stockAction:'none',equipmentAction:'none'});}} className={inputClass}>{kinds.map(kind=><option key={kind.value} value={kind.value}>{kind.label}</option>)}</select></Field>{!simplePurchase&&<Field label="TTC (CHF)"><NumberInput aria-label={`Montant ligne ${index+1}`} value={line.amount} onValue={amount=>{updateLine(line.id,{amount});if(draft.lines.length===1)patch({amount});}} emptyValue={undefined} className={`${inputClass} tabular-nums`}/></Field>}</div>
          {line.evidence?<details className="text-xs text-cave-400"><summary className="cursor-pointer min-h-8 flex items-center">Voir l’extrait du document</summary><p className="text-cave-300 leading-relaxed">{line.evidence}</p></details>:null}
          {['ingredient','packaging','cleaning'].includes(line.kind)?<div className="space-y-2"><label className="text-sm text-cave-300 flex items-center gap-2"><Package size={16}/>Réception en stock</label><select aria-label={`Stock ligne ${index+1}`} value={line.stockAction} onChange={e=>updateLine(line.id,{stockAction:e.target.value as any})} className={inputClass}><option value="none">Aucun mouvement de stock</option><option value="existing">Ajouter à un article existant</option><option value="new">Créer un nouvel article</option></select>{line.stockAction==='existing'?<Combobox ariaLabel="Article" value={line.stockRef||''} onChange={stockRef=>updateLine(line.id,{stockRef})} options={stockOptions} placeholder="Chercher dans le stock"/>:null}{line.stockAction!=='none'?<div className="grid grid-cols-2 gap-2"><Field label="Quantité reçue"><NumberInput aria-label={`Quantité ligne ${index+1}`} value={line.quantity} onValue={quantity=>updateLine(line.id,{quantity})} emptyValue={undefined} min={0} className={inputClass}/></Field><Field label="Unité lue / reçue"><TextInput aria-label={`Unité ligne ${index+1}`} value={line.unit} onChange={unit=>updateLine(line.id,{unit})} placeholder="kg, g, L, sachet…"/></Field></div>:null}</div>:null}
          {line.kind==='equipment'||line.kind==='maintenance'?<div className="space-y-2"><Field label={line.kind==='equipment'?'Fiche matériel':'Matériel entretenu'}><select aria-label={`Matériel ligne ${index+1}`} value={line.equipmentAction} onChange={e=>updateLine(line.id,{equipmentAction:e.target.value as any})} className={inputClass}><option value="none">Ne pas lier de matériel</option>{line.kind==='equipment'?<option value="new">Créer la fiche de ce matériel</option>:null}<option value="existing">Lier un matériel déjà présent</option></select></Field>{line.equipmentAction==='existing'?<Combobox ariaLabel="Matériel" value={line.equipmentRef||''} onChange={equipmentRef=>updateLine(line.id,{equipmentRef})} options={equipmentOptions} placeholder="Chercher un matériel"/>:null}{line.equipmentAction==='new'?<p className="text-xs text-cave-400">La fiche reprendra le prix et la date de cet achat. L’amortissement se renseigne dans Finances → Annuel.</p>:null}</div>:null}
        </article>)}
        <button type="button" disabled={draft.lines.length>=35} onClick={()=>patch({lines:[...draft.lines,newLine()]})} className={`${button} border-dashed border-cave-600 text-cave-300 w-full flex justify-center items-center gap-2`}><Plus size={17}/>Ajouter une ligne</button>
        {draft.lines.length>1?<p className={`text-sm text-right ${Math.abs(draft.lines.reduce((s,line)=>s+(line.amount||0),0)-(draft.amount||0))>0.005?'text-amber-200':'text-cave-400'}`}>Détail : {money(draft.lines.reduce((sum,line)=>sum+(line.amount||0),0))} / {money(draft.amount||0)}</p>:null}
      </div></details>
      <details className="rounded-panel border border-cave-800 p-3"><summary className="min-h-10 flex items-center text-sm text-cave-400 cursor-pointer">Référence et TVA du document{hints.invoiceNumber||hints.tvaAmount||hints.tvaRate?<span className="ml-2 text-amber-200 text-xs">À vérifier</span>:null}</summary><div className="space-y-3 pt-2">{draft.sourceOrderNumber?<p className="text-sm text-cave-300">Commande n° {draft.sourceOrderNumber}</p>:null}<Field label="N° de facture" htmlFor="purchase-invoice-number"><TextInput id="purchase-invoice-number" value={draft.invoiceNumber} onChange={invoiceNumber=>{reviewed('invoiceNumber');patch({invoiceNumber});}}/></Field><ScanHint field="invoiceNumber" message={hints.invoiceNumber}/><div className="grid grid-cols-2 gap-2"><Field label="TVA source (CHF)" htmlFor="purchase-vat"><NumberInput id="purchase-vat" value={draft.sourceVatAmount} onValue={sourceVatAmount=>{reviewed('tvaAmount');patch({sourceVatAmount});}} emptyValue={undefined} className={inputClass}/></Field><Field label="Taux source (%)" htmlFor="purchase-vat-rate"><NumberInput id="purchase-vat-rate" value={draft.sourceVatRate===undefined?undefined:draft.sourceVatRate*100} onValue={value=>patch({sourceVatRate:value===undefined?undefined:value/100})} emptyValue={undefined} className={inputClass}/></Field></div><ScanHint field="tvaAmount" message={hints.tvaAmount}/><ScanHint field="tvaRate" message={hints.tvaRate}/><p className="text-xs text-cave-500">Sans assujettissement TVA, le montant TTC est la dépense. La TVA lue reste conservée avec la source.</p></div></details>
      {duplicates.length?<label className="flex gap-3 p-3 rounded-panel border border-amber-400/30 text-sm text-amber-200"><input type="checkbox" className="mt-1 h-5 w-5" checked={Boolean(draft.duplicateConfirmed)} onChange={e=>setDraft(previous=>({...previous,duplicateConfirmed:e.target.checked}))}/><span>Achat similaire : {duplicates[0].description}, {duplicates[0].date}. J’ai vérifié : il s’agit bien d’un autre achat.</span></label>:null}
      {draft.proofDataUrl?<p className="text-xs text-cave-400">Le justificatif sera rangé dans ton Drive privé à l’enregistrement.</p>:null}
      </fieldset>:null}
    </div>
  </Sheet>;
}
