import { Input, Textarea } from '../Input';
import React, { useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { Sheet } from '../Sheet';
import { NumberInput } from '../NumberInput';
import type { FinanceCategory, Transaction, StockItem } from '../../types';
import type { FinancialProfile, FinancialPlan, FinancialAsset, FinancialClosing, FinancialInventoryLine, FinancialPayment } from '../../domain/finance/types';
import { formatCHF, todayISO, isoDate, transactionAmount, transactionDirection, paymentState } from '../../domain/finance/ledger';
import { FinanceService } from '../../services/financeService';
import { StorageService } from '../../services/storage';

export const CATEGORY_LABELS: Record<FinanceCategory,string> = { brassage:'Brassage', materiel:'Matériel', nettoyage:'Nettoyage', chargesFixes:'Charges fixes', renovation:'Local et travaux', divers:'Autres frais', recettes:'Ventes', apports:'Apports privés' };
export const idFor = (prefix:string) => `${prefix}-${crypto.randomUUID()}`;
export function MoneyInput({label,value,onChange,required=false,signed=false}:{label:string;value:number|undefined;onChange:(v:number|undefined)=>void;required?:boolean;signed?:boolean}) {
  return <label className="finance-field">{label}<NumberInput aria-label={label} value={value == null ? undefined : value/100} onValue={v=>onChange(v == null ? undefined : Math.round(v*100))} emptyValue={undefined} required={required} min={signed?undefined:0} /></label>;
}
export function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="finance-field">{label}{children}</label>; }
function FormSheet({title,onClose,onSave,children,saveLabel='Enregistrer'}:{title:string;onClose:()=>void;onSave:()=>void|Promise<void>;children:React.ReactNode;saveLabel?:string}) {
  const [error,setError]=useState(''), [busy,setBusy]=useState(false);
  const submit=async(e?:React.FormEvent)=>{e?.preventDefault(); if(busy)return; setBusy(true); setError(''); try {await onSave();onClose();}catch(err){setError(err instanceof Error?err.message:'Enregistrement impossible.');}finally{setBusy(false);}};
  return <Sheet open title={title} onClose={onClose} dismissible={!busy} className="finance-sheet" footer={<div className="finance-actions"><button className="finance-action secondary" type="button" onClick={onClose} disabled={busy}>Annuler</button><button type="submit" form="finance-form" className="finance-action" disabled={busy}>{busy?'Enregistrement…':saveLabel}</button></div>}><form autoComplete="off" id="finance-form" onSubmit={submit} className="finance-form">{error&&<p role="alert" className="finance-error">{error}</p>}{children}</form></Sheet>;
}
export function ProfileSheet({profile,onClose}:{profile:FinancialProfile;onClose:()=>void}) {
  const [draft,setDraft]=useState(profile), [cash,setCash]=useState(profile.openingCash?.amountCents), [date,setDate]=useState(profile.openingCash?.date??todayISO()), [confirmed,setConfirmed]=useState(profile.openingCash?.confirmed??false);
  return <FormSheet title="Solde et paramètres financiers" onClose={onClose} onSave={()=>{if(cash!=null&&!isoDate(date))throw Error('Choisis la date du solde.'); FinanceService.saveProfile({...draft,openingCash:cash!=null?{date,amountCents:cash,confirmed}:undefined});}}>
    <p className="finance-muted">Le solde de départ sert à calculer l’argent disponible après les paiements enregistrés.</p>
    <div className="finance-form-grid"><MoneyInput signed label="Solde de départ (CHF)" value={cash} onChange={value=>{setCash(value);setConfirmed(false);}}/>
    <Field label="Date du solde"><input type="date" value={date} max={todayISO()} onChange={e=>{setDate(e.target.value);setConfirmed(false);}} required/></Field></div>
    <label className="finance-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>J’ai vérifié ce solde, avant les paiements de cette journée.</label>
    <details className="finance-disclosure"><summary>Paramètres des prévisions et des brassins</summary><div className="finance-form">
    <Field label="Historique des dépenses complet depuis"><input type="month" value={draft.historyCompleteFrom?.slice(0,7)??''} onChange={e=>setDraft({...draft,historyCompleteFrom:e.target.value?`${e.target.value}-01`:undefined})}/></Field>
    <p className="finance-muted">La tendance n’est calculée qu’avec au moins trois mois complets. Les anciens paiements inconnus restent à confirmer.</p>
    <Field label="Production annuelle prévue (litres conditionnés)"><NumberInput value={draft.annualProductionL} onValue={v=>setDraft({...draft,annualProductionL:v??undefined})} emptyValue={undefined} min={1}/></Field>
    <p className="finance-muted">Cette production permet de répartir les charges fixes entre les brassins. Ton temps personnel n’est pas compté.</p>
    </div></details>
  </FormSheet>;
}
export function PlanSheet({plan,onClose}:{plan?:FinancialPlan;onClose:()=>void}) {
  const [draft,setDraft]=useState<FinancialPlan>(()=>plan??{id:idFor('PREV'),title:'',date:todayISO(),amountCents:0,direction:'out',category:'chargesFixes',source:'manual',status:'active',createdAt:new Date().toISOString()});
  const field=<K extends keyof FinancialPlan>(key:K,value:FinancialPlan[K])=>setDraft({...draft,[key]:value});
  return <FormSheet title={plan?'Modifier la prévision':'Prévoir une dépense'} onClose={onClose} onSave={()=>{if(!draft.title.trim()||draft.amountCents<=0)throw Error('Un libellé et un montant positif sont nécessaires.');FinanceService.savePlan({...draft,title:draft.title.trim()});}}>
    <Field label="Libellé"><Input value={draft.title} onChange={e=>field('title',e.target.value)} placeholder="Loyer, commande de malt, vente prévue…" required/></Field>
    <div className="finance-form-grid"><MoneyInput label="Montant (CHF)" value={draft.amountCents||undefined} onChange={v=>field('amountCents',v??0)} required/><Field label="Date de paiement prévue"><input type="date" value={draft.date} onChange={e=>field('date',e.target.value)} required/></Field></div>
    <Field label="Mouvement"><select value={draft.direction} onChange={e=>field('direction',e.target.value as 'in'|'out')}><option value="out">Argent à payer</option><option value="in">Argent à recevoir</option></select></Field>
    <Field label="Catégorie"><select value={draft.category} onChange={e=>field('category',e.target.value as FinanceCategory)}>{Object.entries(CATEGORY_LABELS).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></Field>
    <Field label="Répétition"><select value={draft.recurrence?.frequency??'none'} onChange={e=>{const freq=e.target.value;setDraft({...draft,source:freq==='none'?'manual':'recurring',recurrence:freq==='none'?undefined:{frequency:freq as 'monthly'|'quarterly'|'yearly'}});}}><option value="none">Une seule fois</option><option value="monthly">Chaque mois</option><option value="quarterly">Chaque trimestre</option><option value="yearly">Chaque année</option></select></Field>
    {draft.recurrence&&<Field label="Fin de la répétition (facultatif)"><input type="date" value={draft.recurrence.endDate??''} onChange={e=>field('recurrence',{...draft.recurrence!,endDate:e.target.value||undefined})}/></Field>}
    {draft.recurrence&&draft.direction==='out'&&<Field label="Coût de revient des brassins"><select value={draft.costAllocation??''} onChange={e=>field('costAllocation',e.target.value as 'fixed'|'brew'||undefined)}><option value="">À confirmer dans le budget du brassin</option><option value="fixed">Charge fixe à répartir (loyer, assurance…)</option><option value="brew">Déjà estimé par brassin (eau, énergie…)</option></select></Field>}
    <Field label="Fournisseur ou client"><Input value={draft.vendor??''} onChange={e=>field('vendor',e.target.value)} /></Field>
    <Field label="Note"><Textarea rows={2} value={draft.notes??''} onChange={e=>field('notes',e.target.value)}/></Field>
    <p className="finance-muted">Cette prévision n’ajoute aucune écriture comptable. Relie la facture à cette prévision lors de son enregistrement.</p>
    {plan&&<Field label="État"><select value={draft.status} onChange={e=>field('status',e.target.value as FinancialPlan['status'])}><option value="draft">Brouillon</option><option value="active">À venir</option><option value="completed">Terminée</option><option value="cancelled">Annulée</option></select></Field>}
  </FormSheet>;
}
const ASSET_CATEGORIES = {tanks:['Cuves et conteneurs',20],furniture:['Installations et mobilier',25],production:['Machines de production',30],electronics:['Informatique et mesure électronique',40],tools:['Outillage et instruments',45],custom:['Taux personnalisé',0]} as const;
export function AssetSheet({asset,onClose}:{asset?:FinancialAsset;onClose:()=>void}) {
  const [draft,setDraft]=useState<FinancialAsset>(()=>asset??{id:idFor('IMMO'),name:'',acquisitionDate:todayISO(),inServiceDate:todayISO(),acquisitionCents:0,businessUsePct:100,category:'production',method:'declining',ratePct:30,openingYear:new Date().getFullYear(),openingValueCents:0,openingConfirmed:false,firstYearFraction:1});
  const equipment=StorageService.getStocks().equipment;
  const allTransactions=StorageService.getTransactions().filter(t=>!t.finance?.voidedAt);
  const transactions=allTransactions.filter(t=>t.finance?.kind!=='refund'&&(t.category==='materiel'||t.finance?.lines.some(l=>l.kind==='equipment')));
  const credits=allTransactions.filter(t=>t.finance?.kind==='refund'&&t.finance.refundOfId===draft.transactionId&&transactionDirection(t,allTransactions)==='in');
  const field=<K extends keyof FinancialAsset>(key:K,value:FinancialAsset[K])=>setDraft({...draft,[key]:value});
  return <FormSheet title={asset?'Modifier l’amortissement':'Ajouter un amortissement'} onClose={onClose} onSave={()=>{if(!draft.name.trim()||draft.acquisitionCents<0||draft.acquisitionCents===0&&!draft.capitalAdjustmentTransactionIds?.length)throw Error('Renseigne le matériel et sa valeur d’acquisition.');FinanceService.saveAsset(draft);}}>
    <Field label="Matériel"><select value={draft.equipmentRef??''} onChange={e=>{const item=equipment.find(x=>x.ref===e.target.value);setDraft({...draft,equipmentRef:item?.ref,name:item?.name??draft.name,acquisitionDate:isoDate(item?.purchaseDate)??draft.acquisitionDate,acquisitionCents:item?.purchasePrice!=null?Math.round(item.purchasePrice*100):draft.acquisitionCents});}}><option value="">Saisie manuelle</option>{equipment.map(e=><option key={e.ref} value={e.ref}>{e.name}</option>)}</select></Field>
    <Field label="Nom de l’immobilisation"><Input value={draft.name} onChange={e=>field('name',e.target.value)} required/></Field>
    <Field label="Achat lié"><select value={draft.transactionId??''} onChange={e=>setDraft({...draft,transactionId:e.target.value||undefined,lineId:undefined,capitalAdjustmentTransactionIds:undefined})}><option value="">Achat ancien ou à relier</option>{transactions.map(t=><option key={t.id} value={t.id}>{t.description} · {formatCHF(transactionAmount(t))}</option>)}</select></Field>
    {draft.transactionId&&<Field label="Ligne de l’achat"><select value={draft.lineId??''} onChange={e=>field('lineId',e.target.value||undefined)}><option value="">Achat complet</option>{transactions.find(t=>t.id===draft.transactionId)?.finance?.lines.map(l=><option key={l.id} value={l.id}>{l.description} · {formatCHF(l.amountCents)}</option>)}</select></Field>}
    <MoneyInput label="Valeur d’acquisition TTC (CHF)" value={draft.acquisitionCents||undefined} onChange={v=>field('acquisitionCents',v??0)} required/>
    {credits.length>0&&<div className="finance-item-editor"><p className="font-semibold">Avoirs sur cet achat</p><p className="finance-muted">Corrige la valeur d’acquisition ci-dessus, puis coche les avoirs déjà déduits de ce coût. Pour un ancien bien, vérifie aussi sa valeur comptable d’ouverture.</p>{credits.map(credit=><label className="finance-check" key={credit.id}><input type="checkbox" checked={draft.capitalAdjustmentTransactionIds?.includes(credit.id)??false} onChange={e=>field('capitalAdjustmentTransactionIds',e.target.checked?[...(draft.capitalAdjustmentTransactionIds??[]),credit.id]:(draft.capitalAdjustmentTransactionIds??[]).filter(id=>id!==credit.id))}/>{credit.description} · {formatCHF(transactionAmount(credit))}</label>)}</div>}
    <div className="finance-form-grid"><Field label="Date d’achat"><input type="date" value={draft.acquisitionDate} onChange={e=>field('acquisitionDate',e.target.value)} required/></Field><Field label="Mise en service"><input type="date" value={draft.inServiceDate} onChange={e=>field('inServiceDate',e.target.value)} required/></Field></div>
    <Field label="Catégorie AFC à confirmer"><select value={draft.category} onChange={e=>{const category=e.target.value as FinancialAsset['category'];setDraft({...draft,category,ratePct:ASSET_CATEGORIES[category][1]/(draft.method==='linear'?2:1)});}}>{Object.entries(ASSET_CATEGORIES).map(([key,[label]])=><option key={key} value={key}>{label}</option>)}</select></Field>
    <div className="finance-form-grid"><Field label="Méthode"><select value={draft.method} onChange={e=>{const method=e.target.value as FinancialAsset['method'];setDraft({...draft,method,ratePct:ASSET_CATEGORIES[draft.category][1]/(method==='linear'?2:1)});}}><option value="declining">Dégressive</option><option value="linear">Linéaire</option></select></Field><Field label="Taux annuel (%)"><NumberInput value={draft.ratePct} onValue={v=>field('ratePct',v??0)} min={0} max={100}/></Field></div>
    <div className="finance-form-grid"><Field label="Part professionnelle (%)"><NumberInput value={draft.businessUsePct} onValue={v=>field('businessUsePct',v??0)} min={0} max={100}/></Field><Field label="Première année retenue"><NumberInput value={draft.openingYear} onValue={v=>field('openingYear',v??new Date().getFullYear())} min={1900} max={2200}/></Field></div>
    <MoneyInput label="Valeur professionnelle restante à l’ouverture (CHF)" value={draft.openingValueCents} onChange={v=>field('openingValueCents',v??0)}/>
    <Field label="Fraction de la première année (1 = année entière)"><NumberInput value={draft.firstYearFraction} onValue={v=>field('firstYearFraction',v??0)} min={0} max={1}/></Field>
    <label className="finance-check"><input type="checkbox" checked={draft.openingConfirmed} onChange={e=>field('openingConfirmed',e.target.checked)}/>Je confirme la catégorie, les valeurs d’ouverture et le traitement de la première année.</label>
    <p className="finance-muted">Les années précédentes ne sont pas recalculées. Pour un bien neuf, la valeur d’ouverture est nulle ; l’acquisition est ajoutée dans son année.</p>
    <details><summary>Cession du matériel</summary><div className="finance-form"><Field label="Date de cession"><input type="date" value={draft.disposedDate??''} onChange={e=>field('disposedDate',e.target.value||undefined)}/></Field><MoneyInput label="Produit de la cession (CHF)" value={draft.disposalProceedsCents} onChange={v=>field('disposalProceedsCents',v)}/><Field label="Vente de ce matériel liée"><select value={draft.disposalTransactionId??''} onChange={e=>field('disposalTransactionId',e.target.value||undefined)}><option value="">À relier si déjà enregistrée dans les ventes</option>{StorageService.getTransactions().filter(t=>t.category==='recettes'&&!t.finance?.voidedAt).map(t=><option key={t.id} value={t.id}>{t.description} · {formatCHF(transactionAmount(t))}</option>)}</select></Field><p className="finance-muted">Relie la vente déjà enregistrée pour compter son produit une seule fois.</p></div></details>
  </FormSheet>;
}
export function ClosingSheet({closing,year,onClose,stockItems}:{closing?:FinancialClosing;year:number;onClose:()=>void;stockItems:StockItem[]}) {
  const [draft,setDraft]=useState<FinancialClosing>(()=>closing??{id:`CLOTURE-${year}`,year,createdAt:new Date().toISOString(),openingInventory:[],closingInventory:[],inventoriesConfirmed:false,adjustments:[]});
  const [side,setSide]=useState<'openingInventory'|'closingInventory'>('closingInventory');
  const update=(index:number,patch:Partial<FinancialInventoryLine>)=>setDraft({...draft,[side]:draft[side].map((l,i)=>i===index?{...l,...patch}:l),inventoriesConfirmed:false});
  const add=()=>setDraft({...draft,[side]:[...draft[side],{id:idFor('INV'),name:'',kind:'raw',quantity:0,unit:'kg',valueCents:0}],inventoriesConfirmed:false});
  return <FormSheet title={`Inventaire et clôture ${year}`} onClose={onClose} onSave={()=>{if([...draft.openingInventory,...draft.closingInventory].some(l=>!l.name.trim()))throw Error('Nomme chaque ligne d’inventaire.');FinanceService.saveClosing(draft);}} saveLabel="Conserver le brouillon">
    <p className="finance-muted">Renseigne les quantités et valeurs aux dates de l’exercice, y compris la bière en fermentation et conditionnée. Le stock actuel ne représente pas automatiquement le stock du 31 décembre.</p>
    <Field label="Inventaire"><select value={side} onChange={e=>setSide(e.target.value as typeof side)}><option value="openingInventory">Ouverture au 1er janvier {year}</option><option value="closingInventory">Clôture au 31 décembre {year}</option></select></Field>
    {!draft[side].length&&<button type="button" className="finance-action secondary" onClick={()=>setDraft({...draft,[side]:stockItems.map(s=>({id:idFor('INV'),name:s.name,kind:s.category==='Emballage'?'packaging':'raw',quantity:s.currentStock,unit:s.unit,valueCents:0,stockItemRef:s.ref,note:'Copié du stock actuel : quantité et valeur à vérifier.'})),inventoriesConfirmed:false})}>Reprendre les articles actuels à vérifier</button>}
    {draft[side].map((line,i)=><div className="finance-item-editor" key={line.id}><Field label="Article ou brassin"><Input value={line.name} onChange={e=>update(i,{name:e.target.value})} required/></Field><Field label="Nature"><select value={line.kind} onChange={e=>update(i,{kind:e.target.value as FinancialInventoryLine['kind']})}><option value="raw">Matières</option><option value="packaging">Emballages</option><option value="cleaning">Nettoyage</option><option value="work-in-progress">Bière en cours</option><option value="finished">Bière conditionnée</option></select></Field><div className="finance-form-grid"><Field label="Quantité"><NumberInput value={line.quantity} onValue={v=>update(i,{quantity:v??0})} min={0}/></Field><Field label="Unité"><Input value={line.unit} onChange={e=>update(i,{unit:e.target.value})}/></Field></div><MoneyInput label="Valeur totale de cette ligne (CHF)" value={line.valueCents} onChange={v=>update(i,{valueCents:v??0})}/><button type="button" className="finance-link" onClick={()=>setDraft({...draft,[side]:draft[side].filter((_,n)=>n!==i),inventoriesConfirmed:false})}><Trash2 size={16}/>Retirer cette ligne</button></div>)}
    <button type="button" className="finance-action secondary" onClick={add}><Plus size={18}/>Ajouter une ligne</button>
    <label className="finance-check"><input type="checkbox" checked={draft.inventoriesConfirmed} onChange={e=>setDraft({...draft,inventoriesConfirmed:e.target.checked})}/>J’ai vérifié les deux inventaires, leurs quantités et leurs valeurs aux dates indiquées.</label>
    <details><summary>Ajustements annuels documentés</summary><div className="finance-form">{draft.adjustments.map((a,i)=><div className="finance-item-editor" key={a.id}><Field label="Motif"><Input value={a.label} onChange={e=>setDraft({...draft,adjustments:draft.adjustments.map((v,n)=>n===i?{...v,label:e.target.value}:v)})}/></Field><Field label="Effet sur le résultat (CHF, signé)"><NumberInput value={a.amountCents/100} onValue={v=>setDraft({...draft,adjustments:draft.adjustments.map((a,n)=>n===i?{...a,amountCents:Math.round((v??0)*100)}:a)})}/></Field><Field label="Justification"><Textarea value={a.note} onChange={e=>setDraft({...draft,adjustments:draft.adjustments.map((a,n)=>n===i?{...a,note:e.target.value}:a)})}/></Field></div>)}<button type="button" className="finance-action secondary" onClick={()=>setDraft({...draft,adjustments:[...draft.adjustments,{id:idFor('AJ'),label:'',amountCents:0,note:''}]})}>Ajouter un ajustement</button></div></details>
    <Field label="Notes de clôture"><Textarea rows={2} value={draft.notes??''} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field>
  </FormSheet>;
}
export function PaymentSheet({transaction,payments,transactions,onClose}:{transaction:Transaction;payments:FinancialPayment[];transactions:Transaction[];onClose:()=>void}) {
  const state=paymentState(transaction,payments,transactions), [amount,setAmount]=useState<number|undefined>(state.remainingCents), [date,setDate]=useState(()=>state.state==='unknown'?'':todayISO()), [method,setMethod]=useState<FinancialPayment['method']>('bank');
  const [paymentId]=useState(()=>idFor('PAI'));
  return <FormSheet title={transactionDirection(transaction,transactions)==='in'?'Enregistrer un encaissement':'Enregistrer un paiement'} onClose={onClose} onSave={()=>{if(!amount||amount>state.remainingCents)throw Error('Le paiement doit être positif et ne pas dépasser le restant dû.');FinanceService.recordPayment({id:paymentId,transactionId:transaction.id,date,amountCents:amount,direction:transactionDirection(transaction,transactions),method,recordedAt:new Date().toISOString()});}}>
    <p>{transaction.description}</p><p className="finance-muted">Montant de la pièce : {formatCHF(transactionAmount(transaction))}. Restant : {formatCHF(state.remainingCents)}.</p>
    {state.state==='unknown'&&<p className="finance-notice">Le paiement historique est inconnu. Indique la date et le montant réellement réglés.</p>}
    <MoneyInput label="Montant réglé (CHF)" value={amount} onChange={setAmount} required/>
    <Field label="Date réelle du paiement"><input type="date" value={date} max={todayISO()} onChange={e=>setDate(e.target.value)} required/></Field>
    <Field label="Moyen de paiement"><select value={method} onChange={e=>setMethod(e.target.value as FinancialPayment['method'])}><option value="bank">Virement bancaire</option><option value="cash">Espèces</option><option value="twint">TWINT</option><option value="other">Autre</option></select></Field>
  </FormSheet>;
}
